# Example configuration for ColorLogic light with favorite colors

light:
  - platform: colorlogic
    entity_id: switch.pool_light_switch  # Your existing pool light switch entity
    name: "Pool Light"                   # This creates a new entity: light.pool_light

button:
  - platform: colorlogic
    entity_id: light.pool_light  # Must reference the light entity created above (NOT the switch!)
    name: "Pool Light"           # This creates: button.pool_light_reset and button.pool_light_next_color

switch:
  - platform: colorlogic
    entity_id: light.pool_light  # Must reference the light entity created above
    name: "Pool Light"           # This creates: switch.pool_light_power

# Add this to your dashboard/lovelace configuration:
# This defines the favorite colors that appear as preset buttons in the UI
type: light
entity: light.pool_light
favorite_colors:
  - rgb_color: [20, 76, 135]    # Deep Sea Blue
  - rgb_color: [7, 112, 174]    # Royal Blue
  - rgb_color: [36, 190, 235]   # Afternoon Skies
  - rgb_color: [20, 185, 187]   # Aqua Green
  - rgb_color: [5, 161, 85]     # Emerald
  - rgb_color: [228, 242, 251]  # Cloud White
  - rgb_color: [233, 36, 50]    # Warm Red
  - rgb_color: [240, 90, 124]   # Flamingo
  - rgb_color: [170, 82, 130]   # Vivid Violet
  - rgb_color: [124, 74, 149]   # Sangria